export const CREATE_USER = "CREATE_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const RETREIVE_USER = "RETREIVE_USER";

export const SUCCESS_NOTIFICATION = "SUCCESS_NOTIFICATION";
export const RESET_NOTIFICATION = "RESET_NOTIFICATION";
export const ERROR_NOTIFICATION = "ERROR_NOTIFICATION";
